name: Build and Deploy Game
on: [push]
jobs:
  build-n-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Pygbag
        run: pip install pygbag
      - name: Build Website
        run: python3 -m pygbag --build $GITHUB_WORKSPACE/game/main.py
      - name: Deploy to Pages
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: game/build/web
